name: Next.js CI

on:
  push:
    branches-ignore:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
          cache: 'npm'

      - uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.{ts,tsx,js,jsx,json}

      - name: Install node_modules
        run: |
          npm ci
          npm run apigen

      - name: Run Prettier
        run: |
          npx prettier --write ${{ env.GIT_DIFF_FILTERED }}
        if: env.GIT_DIFF
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply Prettier Change

      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-review
          eslint_flags: 'src/**/*.{ts,tsx}'
          fail_on_error: true

      - name: Build
        run: npm run build
        env:
          NEXT_PUBLIC_API_KEY: ${{ vars.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_AUTH_DOMAIN: ${{ vars.NEXT_PUBLIC_AUTH_DOMAIN }}
          NEXT_PUBLIC_PROJECT_ID: ${{ vars.NEXT_PUBLIC_PROJECT_ID }}
          NEXT_PUBLIC_STORAGE_BUCKET: ${{ vars.NEXT_PUBLIC_STORAGE_BUCKET }}
          NEXT_PUBLIC_MESSAGING_SENDER_ID: ${{ vars.NEXT_PUBLIC_MESSAGING_SENDER_ID }}
          NEXT_PUBLIC_APP_ID: ${{ vars.NEXT_PUBLIC_APP_ID }}
          NEXT_PUBLIC_MEASUREMENT_ID: ${{ vars.NEXT_PUBLIC_MEASUREMENT_ID }}
