# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - airship

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://airship.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_b57b1b3d1e854cadbaacad28c7f5a4ea }}
        password: ${{ secrets.AzureAppService_ContainerPassword_80022532531d4958a79627375deaa13b }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        build-args: |
          NEXT_PUBLIC_API_ORIGIN=${{ vars.NEXT_PUBLIC_API_ORIGIN }}
          NEXT_PUBLIC_API_KEY=${{ vars.NEXT_PUBLIC_API_KEY }}
          NEXT_PUBLIC_AUTH_DOMAIN=${{ vars.NEXT_PUBLIC_AUTH_DOMAIN }}
          NEXT_PUBLIC_PROJECT_ID=${{ vars.NEXT_PUBLIC_PROJECT_ID }}
          NEXT_PUBLIC_STORAGE_BUCKET=${{ vars.NEXT_PUBLIC_STORAGE_BUCKET }}
          NEXT_PUBLIC_MESSAGING_SENDER_ID=${{ vars.NEXT_PUBLIC_MESSAGING_SENDER }}
          NEXT_PUBLIC_APP_ID=${{ vars.NEXT_PUBLIC_APP_ID }}
          NEXT_PUBLIC_MEASUREMENT_ID=${{ vars.NEXT_PUBLIC_MEASUREMENT_ID }}
        tags: airship.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b57b1b3d1e854cadbaacad28c7f5a4ea }}/airship-frontend:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'airship'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_e3a8291962474be18484d59706caa8d7 }}
        images: 'airship.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_b57b1b3d1e854cadbaacad28c7f5a4ea }}/airship-frontend:${{ github.sha }}'
